/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MandelBrot_double;

import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 *
 * @author parke
 */
public class Frame extends javax.swing.JFrame {
    
    private boolean jul = false;
    
    public Frame(int xSize, int ySize) {
        initComponents();
        jPanel1.setSize(xSize, ySize);
        jPanel1.setPreferredSize(new Dimension(xSize, ySize));
        
        this.pack();
        this.setVisible(true);
    }
    
    public void updateDisplay(BufferedImage image) {
        jPanel1.getGraphics().drawImage(image, 0, 0, jPanel1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
        if (evt.getButton() == 3) {
            jul = !jul;
            if (!jul) {
                MandelBrot_double.calculateScreen(null);
            }
        } else {
            double[] pos = getMouseFractPos(evt.getX(), evt.getY());
            
            double[] temp = MandelBrot_double.getBoundingBox();
            double scale = temp[0] / 1.3;
            
            MandelBrot_double.setBoundingBox(new double[]{scale, pos[0], pos[1]});
            
            MandelBrot_double.calculateScreen(null);
        }

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        
        if (jul) {
            double[] pos = getMouseFractPos(evt.getX(), evt.getY());
            
            MandelBrot_double.calculateScreen(new ComplexNumber(pos[0], pos[1]));
        }
    }//GEN-LAST:event_jPanel1MouseMoved
    
    private double[] getMouseFractPos(int mouseXPos, int mouseYPos) {
        
        double[] temp = MandelBrot_double.getBoundingBox();
        
        double xPos = mouseXPos / (double) jPanel1.getWidth();
        xPos = (xPos - 0.5) * 2;
        double yPos = mouseYPos / (double) jPanel1.getHeight();
        yPos = (yPos - 0.5) * 2;

        //System.out.println(xPos + " " + yPos);
        double xDiff = (temp[0] * 2) - temp[0];
        double yDiff = (temp[0] * 2) - temp[0];
        
        xPos = (xPos * xDiff) + temp[1];
        yPos = (yPos * yDiff) + temp[2];
        
        return new double[]{xPos, yPos};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
